name: cognix
description: "Cognix is your AI-powered academic assistant, a sleek Flutter app for web and mobile that helps you effortlessly analyze text and master your studies."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  go_router: ^16.2.0
  file_picker: ^10.3.8
  google_fonts: ^6.3.3
  http:
  http_parser: ^4.0.2
  share_plus: ^10.0.2 
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  uuid: ^4.5.2 
  path_provider: ^2.1.5
  open_file: ^3.5.10
  flutter_card_swiper: ^7.2.0
  awesome_dialog: ^3.3.0
  flutter_spinkit: ^5.2.2
  permission_handler: ^11.3.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/cognix_launch.png
  remove_alpha_ios: true
